# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=200)),
                ('timer', models.DurationField(default=0)),
                ('done', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('finished', models.DateField(auto_now=True)),
            ],
        ),
    ]
